[package]
name = "yuki"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
websocket = "0.27.0"

[dependencies.async-std]
version = "1.12.0"
features = ["attributes"]
